name: NewPlayerWorld-Maski
version: '${project.version}'
main: com.mcmiddleearth.introduction.IntroductionPlugin
api-version: 1.21
authors: [ Eriol_Eandur ]
description: Short new player intro with compatibility check.

