name: '${project.artifactId}'
version: '${project.version}'
main: com.mcmiddleearth.introduction.IntroductionPlugin
api-version: 1.21
authors: [ Eriol_Eandur ]
depends: [ MCME-Architect, ViaVersion ]
description: Short new player intro with compatibility check.

commands:
  ignoreissue:
    description: Ignores compatibility issues
    usage: /ignore
